# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-27 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrafanaDashBoards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_dashboard', models.CharField(blank=True, max_length=80, unique=True)),
                ('link', models.CharField(blank=True, max_length=150, unique=True)),
                ('title', models.CharField(blank=True, max_length=80)),
                ('version', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrafanaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_organizacion', models.CharField(blank=True, max_length=80, unique=True)),
                ('token_admin', models.CharField(blank=True, max_length=100, unique=True)),
                ('token_viewer', models.CharField(blank=True, max_length=100, unique=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_grafana', to='graficas.Empresa')),
            ],
        ),
    ]
