# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-27 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graficas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grafanadashboards',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_dashboard', to='graficas.Empresa'),
        ),
    ]
