# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-27 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graficas', '0003_auto_20200827_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='grafanadata',
            name='id_org',
            field=models.IntegerField(null=True),
        ),
    ]
